# -*- coding: utf-8 -*-
"""SeedStocks2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDXsb4WOglFckj9AbdMJwaungtcjdQGl
"""

import pandas as pd
# Sets the raw url variable to a google drive link
google_drive_url = "https://docs.google.com/spreadsheets/d/1E_wNkaGU22AwCGc4p-bo_YujfPT1pvNq/edit?usp=share_link&ouid=111659708370824727716&rtpof=true&sd=true"
# Changes the google drive URL to 
raw_url = 'https://drive.google.com/uc?id=' + google_drive_url.split('/')[-2]

# Declare the sheet names that you are wanting to pull data from
sheet_names = ["Customers",
               "Employees",
               "Accounts",
               "StockPortfolio",
               "Stocks",
               "Transactions",
               "StockTransactions",
               "Disputes",
              ]

data = pd.read_excel(raw_url, sheet_name = sheet_names)

data["Stocks"]

PROJECT_NAME = "fa22_finalproject_32"

def using_statements():
  """Returns the using statements and adds the opening brackets necessary for"""
  
  
  
  return f"""
using {PROJECT_NAME}.DAL;
using {PROJECT_NAME}.Models;
using {PROJECT_NAME}.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace {PROJECT_NAME}.Seeding
{{
"""

# Instantiate a string to hold the customers seeding text
customers_string = ""

# Adds the using statements necessary for the C# code to work
customers_string += using_statements()

# Adds necessary C# code for adding users, based off of HW3's seeding code.
# No variables are needed so there is no need to make it an f-string
customers_string += """
    public static class SeedStocks
    {
        public static void SeedAllStocks(AppDbContext db)
        {
            List<Stock> AllStocks = new List<Stock>();

"""

print(customers_string)

for stock in data["Stocks"].to_dict(orient="records"):
  # For each customer in the data, create new lines of code that specify the User's properties
  customers_string += f"""
            AllStocks.Add(new Stock()
            {{
                    StockTicker = "{stock["TickerSymbol"]}",
                    StockName = "{stock["Name"]}",
                    Price = {stock["Price"]}m,
                    StockType = "{stock["StockType"]}"

            }});
"""

print(customers_string)

customers_string += f"""
            //create a counter and flag to help with debugging
            int intStockID = 0;

            //we are now going to add the data to the database
            //this could cause errors, so we need to put this code
            //into a Try/Catch block
            try
            {{
                //loop through each of the Stocks
                foreach (Stock seedStock in AllStocks)
                {{
                    //updates the counters to get info on where the problem is
                    intStockID = seedStock.StockID;

                    //try to find the Stock in the database
                    Stock dbStock = db.Stocks.FirstOrDefault(c => c.StockID == seedStock.StockID);

                    //if the Stock isn't in the database, dbStock will be null
                    if (dbStock == null)
                    {{
                        //add the Stock to the database
                        db.Stocks.Add(seedStock);
                        db.SaveChanges();
                    }}
                    else //the record is in the database
                    {{
                        //update all the fields
                        //this isn't really needed for Stock because it only has one field
                        //but you will need it to re-set seeded data with more fields
                        dbStock.TickerSymbol = seedStock.TickerSymbol;
                        dbStock.StockName = seedStock.StockName;
                        dbStock.StockPrice = seedStock.StockPrice;
                        dbStock.StockType = seedStock.StockType;
                        //you would add other fields here
                        db.SaveChanges();
                    }}

                }}
            }}
            catch (Exception ex) //something about adding to the database caused a problem
            {{
                //create a new instance of the string builder to make building out 
                //our message neater - we don't want a REALLY long line of code for this
                //so we break it up into several lines
                StringBuilder msg = new StringBuilder();

                msg.Append("There was an error adding the ");
                msg.Append(" Stock (StockID = ");
                msg.Append(intStockID);
                msg.Append(")");

                //have this method throw the exception to the calling method
                //this code wraps the exception from the database with the 
                //custom message we built above. The original error from the
                //database becomes the InnerException
                throw new Exception(msg.ToString(), ex);
            }}
  
        }}
    }}
        
}}
"""



file = open("SeedStocks.cs", "w")
file.write(customers_string)
file.close()

print(customers_string)